### ISSUE TITLE
Getting exception while starting the monitoring project.

### ISSUE THREAD

**Issue by akshay3688** [StephenOTT/Camunda-Monitoring#21]
HI @StephenOTT 

Thanks for amazing plugin and all your contribution. 

When I run docker-compose up I see below exception in camunda-monitoring 

 Description:
camunda-monitoring    |
camunda-monitoring    | An attempt was made to call a method that does not exist. The attempt was made from the following location:
camunda-monitoring    |
camunda-monitoring    |     org.springframework.boot.sql.init.dependency.
DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor.getDetectors(DatabaseInitializationDependencyConfigurer.java:165)
camunda-monitoring    |
camunda-monitoring    | The following method did not exist:
camunda-monitoring    |
camunda-monitoring    |     'java.util.List org.springframework.boot.util.Instantiator.instantiate(java.lang.ClassLoader, java.util.Collection)'
camunda-monitoring    |
camunda-monitoring    | The method's class, org.springframework.boot.util.Instantiator, is available from the following locations:
camunda-monitoring    |
camunda-monitoring    |     jar:file:/camunda/configuration/userlib/Camunda-Monitoring.jar!/org/springframework/boot/util/Instantiator.class
camunda-monitoring    |     jar:file:/camunda/internal/camunda-bpm-run-core.jar!/BOOT-INF/lib/spring-boot-2.5.4.jar!/org/springframework/boot/util/Instantiator.class
camunda-monitoring    |
camunda-monitoring    | The class hierarchy was loaded from the following locations:
camunda-monitoring    |
camunda-monitoring    |     org.springframework.boot.util.Instantiator: file:/camunda/configuration/userlib/Camunda-Monitoring.jar
camunda-monitoring    |
camunda-monitoring    |
camunda-monitoring    | Action:
camunda-monitoring    |
camunda-monitoring    | Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.util.Instantiator

Can you please let me know with which base image of "camunda-bpm-platform" it will work with ?

 I tried version 7.14 and 7.13 I am getting 

camunda-monitoring    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
camunda-monitoring    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
camunda-monitoring    | Exception in thread "main" java.lang.reflect.InvocationTargetException
camunda-monitoring    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
camunda-monitoring    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
camunda-monitoring    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
camunda-monitoring    |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
camunda-monitoring    |         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
camunda-monitoring    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
camunda-monitoring    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
camunda-monitoring    |         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
camunda-monitoring    | Caused by: java.lang.IllegalStateException: No suitable logging system located

with those two versions ?

**Comment by akshay3688** [comment]
https://github.com/StephenOTT/Camunda-Monitoring/issues/19 This helped. Thanks !
